<?xml version="1.0"?>
<package format="3">
  <name>pybullet_arm_bringup</name>
  <version>0.1.0</version>
  <description>Launch files and configuration for the ROS 2 PyBullet arm lab.</description>
  <maintainer email="student@example.com">chengxunlinux</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>pybullet_arm_control</exec_depend>
  <exec_depend>pybullet_arm_description</exec_depend>
  <exec_depend>pybullet_arm_sim</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
