<?xml version="1.0"?>
<package format="3">
  <name>pybullet_arm_sim</name>
  <version>0.1.0</version>
  <description>PyBullet physics engine and ROS 2 adapter for the arm lab.</description>
  <maintainer email="student@example.com">chengxunlinux</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pybullet_arm_interfaces</depend>
  <depend>rclpy</depend>
  <depend>rosgraph_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>trajectory_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>xacro</depend>

  <test_depend>pybullet_arm_description</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
